server:
  port: 8080

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

netty:
  socket:
    port: 7397
  websocket:
    port: 7398